[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[profile.stage1]
inherits = "dev"
strip = true
opt-level = "s"
lto = true
codegen-units = 1
debug = false
overflow-checks = false
panic = "abort" 

